import Link from "next/link"
import { ArrowRightIcon, FileOutputIcon, PlusIcon } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { reports } from "@/lib/data/product-seed"

const variants = {
  PASS: "success",
  CONDITIONAL_PASS: "warning",
  FAIL: "destructive",
} as const

export function ReportList() {
  return (
    <>
      <div className="flex items-center gap-2 border-b p-3">
        <Input
          placeholder="Search report number or application…"
          className="max-w-80"
        />
        <Button variant="outline" size="sm">
          All results
        </Button>
        <Button className="ml-auto" size="sm">
          <PlusIcon data-icon="inline-start" />
          Generate Report
        </Button>
      </div>
      <div className="overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report number</TableHead>
              <TableHead>Application</TableHead>
              <TableHead>Release</TableHead>
              <TableHead>Environment</TableHead>
              <TableHead>Result</TableHead>
              <TableHead>Generated by</TableHead>
              <TableHead>Generated at</TableHead>
              <TableHead>
                <span className="sr-only">Open</span>
              </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {reports.map((report) => (
              <TableRow key={report.id}>
                <TableCell>
                  <Link
                    href={`/reports/${report.id}`}
                    className="inline-flex items-center gap-2 font-mono text-xs font-medium hover:underline"
                  >
                    <FileOutputIcon className="size-4" />
                    {report.number}
                  </Link>
                </TableCell>
                <TableCell className="font-medium">
                  {report.application}
                </TableCell>
                <TableCell>{report.release}</TableCell>
                <TableCell>
                  <Badge variant="outline">{report.environment}</Badge>
                </TableCell>
                <TableCell>
                  <Badge variant={variants[report.result]}>
                    {report.result.replaceAll("_", " ")}
                  </Badge>
                </TableCell>
                <TableCell>{report.generatedBy}</TableCell>
                <TableCell className="whitespace-nowrap text-muted-foreground">
                  {report.generatedAt}
                </TableCell>
                <TableCell>
                  <Button
                    variant="ghost"
                    size="icon-sm"
                    render={<Link href={`/reports/${report.id}`} />}
                    aria-label={`Open ${report.number}`}
                  >
                    <ArrowRightIcon />
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </>
  )
}
